#!/bin/bash -e

if [ ! -s /etc/bind/rndc.key ]; then
rndc-confgen -r /dev/urandom -a
fi

chmod 2755 /etc/bind
chmod 644 /etc/bind/*
chown -R root:root /etc/bind
chown root:bind /etc/bind/named.conf
chown root:bind /etc/bind/named.conf.default-zones
chown root:bind /etc/bind/named.conf.local
chown root:bind /etc/bind/named.conf.options

chmod 640 /etc/bind/rndc.key
chown bind:bind /etc/bind/rndc.key

exec /usr/sbin/named -c /etc/bind/named.conf -f
